AttributeTags.
  #增加玩家的攻击力属性
  Damage:
    - "攻击力"
  #增加玩家的防御力属性
  Defense:
    - "防御力"
  #增加玩家的护甲值，百分比抵消攻击力屋性
  Armor:
    - "护甲值”
  #减少攻击玩家的护甲值属性
  BreakArmor:
    - "护甲忽视"
  #增加玩家的最大生命上限
  Health:
    - "生命上限"
  #暴击的几率
  CritChance:
    -"暴击几率"
  #暴击的倍率
  Crit:
    - "暴击倍率"
  #吸血几率
  StealChance
    -"生命窃取几率"
  #吸血倍率
  StealLife:
    - "生命窃取倍率"
  #无视此次攻击的概率
  Dodge:
    - "闪避几率"
  #减少对方闪避几率的屋性
  HitRate:
    - "命中概率”
  #触发格挡的概率
  Block:
    - "格挡几率"
  #百分比格挡受到的伤害
  BlockRate:
    - "格挡伤害"
  #百分比概率无视护甲值，但会计算防御力
  IgnoreArmor:
    - "无视护甲"
  #可无视防御对对方造成伤害，但会计算护甲值
  IgnoreDefense:
    - "无视防御"
  #增加玩家移动速度
  MoveSpeed:
    - "移动速度"
  SellPrice:
    - "出售后可获得金币"
  SellPoint:
    - "出售后可获得点券:
SuffixTag:
  #带有此后缀的属性，将以百分比的形式增加玩家属性
  Percentange: "(%)"
  #带有此后缀的厘性，将以倍率的形式增加玩家的屋性，部分属性不可用，在不可用的屋性上，将会转换
  #即1为100%
  RateTag: "(x)"
ConditionTag:
  #全局属性条件设置
  GlobalCondition:
  #全局限制玩家等级，可用格式如下
  #等级限制: 20
  #等级限制: 10~ 20
  LevelTag: "等级限制"
  #全局限制玩家职业，可用格式如下
  #职业限制: 战士
  #职业限制: 战士/法师/盗贼
  ClassTag:
    Tag: "职业限制"
    Split: "/"
  #限制全局厘性只在主手生效
  MainHandTag:
    - "该武器仅可用于主手槽位"
    - "主手武器"
  OffHandTag:
    - "该武器仅可用于副手槽位"
    - "副手武器"
  HelmetTag:
    - "该武器仅可用于头盔槽位"
    - "头盔"
  ChestplateTag:
    - "该武器仅可用于胸甲槽位"
    - "胸甲"
  LeggingsTag:
    - "该武器仅可用于护腿槽位"
    - "护腿"
  BootsTag:
    - "该武器仅可用于靴子槽位"
    - "靴子"
#单屋性条件设置
LimitedCondition:
  #限制玩家等级使用厘性，可用格式如下
  #等级限制: 20
  #等级限制: 10~20
  LevelTag: "等级限制"
  #限制玩家职业使用雇性，可用格式如下
  #职业限制: 战士
  #职业限制: 战士/法师/盗贼
  ClassTag:
    Tag: "职业限制"
    Split: "/"
    #限制该条只能在主手使用
  MainHandTag:
    - "该属性生效于主手"
    - "主手属性"
  OffHandTag:
    - "该属性生效于副手"
    - "副手属性"
  HelmetTag:
    - "该属性生效于头盔"
    - "头盔属性"
  ChestplateTag:
    - "该属性生效于护甲"
    - "护甲属性"
  LeggingsTag:
    - "该属性生效于护腿"
    - "护腿属性"
  BootsTag:
    - "该属性生效于靴子"
    - "靴子属性"
